version: '3.8'

services:
  meu-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      # Descomente se usar H2 com persistência em arquivo
       - h2data:./data/testdb
volumes:
  # h2data:
